version: "3.4"
x-environment:
  &QUICKSTART_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}
services:
  go:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./go/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
    labels:
      - traefik.enable=true
      - traefik.http.routers.plaid-api-go.rule=Host(`plaid.goodfun.io`) && (PathPrefix(`/api/all/transactions/csv`) || PathPrefix(`/api/all/balances/csv`))
      - traefik.http.routers.plaid-api-go.entryPoints=websecure
      - traefik.http.routers.plaid-api-go.middlewares=auth@file
      - traefik.http.routers.plaid-api-go.tls=true
      - traefik.http.routers.plaid-api-go.tls.certresolver=plaid
      - traefik.http.services.go.loadbalancer.server.port=8000
      - traefik.http.services.go.loadbalancer.passHostHeader=true
  java:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./java/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  node:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  python:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./python/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  ruby:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  frontend:
    environment:
      - REACT_APP_API_HOST
      - HOST
      - PUBLIC_URL
    networks:
      - "quickstart"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports: ["3000:3000"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.plaid.rule=Host(`plaid.goodfun.io`)
      - traefik.http.routers.plaid.entryPoints=websecure
      - traefik.http.routers.plaid.tls=true
      - traefik.http.routers.plaid.tls.certresolver=plaid
      - traefik.http.services.plaid.loadbalancer.server.port=3000
      - traefik.http.services.plaid.loadbalancer.passHostHeader=true
    hostname: ${HOST}
networks:
  quickstart:
    name: quickstart
